import { afterEach, beforeAll, beforeEach, describe, expect, it } from "vitest";
import { useTestDb } from "@/lib/db";
import { call } from "./helpers/api";
import { registerUser, type TestUser } from "./helpers/routes";
import { resetCache } from "./helpers/db";
import { fixture, mockFetch, type FetchMock } from "./helpers/fetch-mock";
import { newsConfig, type FeedConfig } from "@/market/news/config";
import { parseFeed } from "@/market/news/rss";
import { canonicalUrl, jaccard, normaliseFeedItems, selectNews, titleTokens, type NewsCandidate } from "@/market/news/select";
import { getNews, setNewsFetchers } from "@/market/news/service";
import * as newsRoute from "@/app/api/market/news/route";
import * as refreshRoute from "@/app/api/market/news/refresh/route";

/** SYNTHETIC feeds (tests/fixtures/rss, generated by tests/fixtures/generate-synthetic.mjs); all tests use this fixed clock so results are reproducible */
const NOW = new Date("2026-09-21T17:30:00Z");
const FILES: Record<string, string> = {
  yahoo: "yahoo", cnbc_top: "cnbc_top", cnbc_finance: "cnbc_finance", bloomberg_markets: "bloomberg_markets",
  guardian_business: "guardian_business", bbc_business: "bbc_business", nyt_business: "nyt_business",
  armenpress: "armenpress", newsam: "newsam", google_armenia: "googlenews_armenia", ft: "ft",
};
const cfg = newsConfig();

function allCandidates(): NewsCandidate[] {
  const out: NewsCandidate[] = [];
  for (const feed of cfg.feeds.filter((f) => f.enabled)) {
    out.push(...normaliseFeedItems(parseFeed(fixture("rss", `${FILES[feed.id]}.xml`), feed.id), feed, cfg));
  }
  return out;
}
const fixtureFetch = async (feed: FeedConfig) => fixture("rss", `${FILES[feed.id]}.xml`);

const HEADLINES = [
  "Nasdaq tumbles as chipmaker earnings disappoint investors",
  "Wall Street bank profits beat expectations after strong trading quarter",
  "Oil prices climb on OPEC supply cut speculation",
  "Gold hits record high as dollar weakens",
  "Federal Reserve minutes signal cautious approach to rate cuts",
  "Tesla shares slide after delivery numbers miss forecasts",
  "Amazon announces layoffs across logistics division",
  "Microsoft cloud revenue lifts quarterly results",
  "Inflation cools in Europe as energy costs ease",
  "Nvidia unveils new AI accelerator for data centers",
  "Copper rally stalls amid China demand worries",
  "Bitcoin surges past resistance as ETF inflows accelerate",
];
const EQUITY_HEADLINES = [
  "Bank earnings beat forecasts and lift stocks",
  "Retailer earnings disappoint as shares slide",
  "Chipmaker guidance lifts Nasdaq to record",
  "Insurer announces buyback and higher dividend",
  "Streaming giant profit tops analyst estimates",
  "Airline revenue jumps ahead of holiday season, earnings up",
];

const cand = (o: Partial<NewsCandidate> & { title: string }): NewsCandidate => ({
  id: `n_${Math.random().toString(16).slice(2, 14)}`,
  source: "Bloomberg",
  feedId: "bloomberg_markets",
  feedName: "Bloomberg",
  url: `https://example.com/${Math.random()}`,
  publishedAt: new Date(NOW.getTime() - 3_600_000).toISOString(),
  region: "global",
  categories: [],
  summary: null,
  imageUrl: null,
  ...o,
});

describe("RSS parsing + normalisation on SYNTHETIC feeds", () => {
  it("every enabled feed parses to headline-only items (no description/body/image fields)", () => {
    for (const feed of cfg.feeds.filter((f) => f.enabled)) {
      const raw = parseFeed(fixture("rss", `${FILES[feed.id]}.xml`), feed.id);
      
      expect(raw.length, feed.id).toBeGreaterThan(5);
      expect(Object.keys(raw[0]).sort().every((k) => ["title", "link", "publishedAt", "categories", "outlet", "summary", "imageUrl"].includes(k))).toBe(true);
    }
    const yahoo = parseFeed(fixture("rss", "yahoo.xml"), "yahoo");
    expect(yahoo[0].outlet).toBeTruthy(); // <source> element
    const ap = parseFeed(fixture("rss", "armenpress.xml"), "armenpress");
    expect(ap.some((i) => i.categories.includes("Economy"))).toBe(true);
    expect(ap[0].title).not.toMatch(/<|\n/);
  });

  it("Google News: title source-suffix stripped and outlet used as the source", () => {
    const feed = cfg.feeds.find((f) => f.id === "google_armenia")!;
    const items = normaliseFeedItems(parseFeed(fixture("rss", "googlenews_armenia.xml"), "g"), feed, cfg);
    expect(items.length).toBeGreaterThan(10);
    for (const i of items.slice(0, 20)) {
      expect(i.source).not.toBe("Google News");
      if (i.outlet) expect(i.title.endsWith(` - ${i.outlet}`)).toBe(false);
    }
  });

  it("canonical URLs: tracking params, fragment, case, trailing slash, param order", () => {
    expect(canonicalUrl("https://WWW.Example.com/a/b/?utm_source=x&b=2&a=1&fbclid=zzz#frag")).toBe("https://www.example.com/a/b?a=1&b=2");
    expect(canonicalUrl("https://example.com/story")).toBe(canonicalUrl("https://example.com/story/?utm_medium=rss"));
    expect(canonicalUrl("https://example.com/")).toBe("https://example.com/");
  });

  it("excluded content (opinion / sport / lifestyle by category, URL or title) never becomes a candidate", () => {
    const feed = cfg.feeds.find((f) => f.id === "guardian_business")!;
    const raw = [
      { title: "Markets rally on rate hopes", link: "https://x.com/business/2026/a", publishedAt: NOW.toISOString(), categories: [] as string[], summary: null, imageUrl: null },
      { title: "Why I love inflation", link: "https://x.com/commentisfree/2026/b", publishedAt: NOW.toISOString(), categories: [], summary: null, imageUrl: null },
      { title: "Cup final preview", link: "https://x.com/sport/c", publishedAt: NOW.toISOString(), categories: [], summary: null, imageUrl: null },
      { title: "Sponsored: buy now", link: "https://x.com/z", publishedAt: NOW.toISOString(), categories: ["Sponsored"], summary: null, imageUrl: null },
      { title: "Watch: the trading floor", link: "https://x.com/d", publishedAt: NOW.toISOString(), categories: [], summary: null, imageUrl: null },
      { title: "No date at all", link: "https://x.com/e", publishedAt: null, categories: [], summary: null, imageUrl: null },
    ];
    expect(normaliseFeedItems(raw, feed, cfg).map((c) => c.title)).toEqual(["Markets rally on rate hopes"]);
  });
});

describe("AC-B5 selection (deterministic, from synthetic fixtures)", () => {
  it("returns exactly 6 items obeying every rule", () => {
    const sel = selectNews(allCandidates(), NOW, cfg);
    expect(sel.items).toHaveLength(6);
    expect(sel.relaxed).toEqual([]); // strict rules were enough
    const bySource = new Map<string, number>();
    const byTopic = new Map<string, number>();
    for (const i of sel.items) {
      bySource.set(i.source, (bySource.get(i.source) ?? 0) + 1);
      byTopic.set(i.topic, (byTopic.get(i.topic) ?? 0) + 1);
      const ageH = (NOW.getTime() - Date.parse(i.publishedAt)) / 3_600_000;
      expect(ageH, i.title).toBeLessThanOrEqual(i.region === "armenia" ? 72 : 48);
      expect(Object.keys(i).sort()).toEqual(["category", "id", "imageUrl", "publishedAt", "region", "source", "summary", "title", "topic", "url"]);
      expect(["Markets", "Economy", "Currencies & Commodities", "Technology", "Armenia", "World"]).toContain(i.category);
      expect(i.id).toMatch(/^[0-9a-f]{16}$/);
      if (i.summary) {
        expect(i.summary.length).toBeLessThanOrEqual(401);
        expect(i.summary).not.toMatch(/<[a-z][^>]*>/i);
      }
      if (i.imageUrl) expect(i.imageUrl).toMatch(/^https:\/\//);
      expect(i.url).toMatch(/^https?:\/\//);
    }
    expect(Math.max(...bySource.values())).toBeLessThanOrEqual(2);
    expect(Math.max(...byTopic.values())).toBeLessThanOrEqual(2);
    const arm = sel.items.filter((i) => i.region === "armenia");
    expect(arm.length).toBeLessThanOrEqual(3);
    expect(sel.counts.armeniaQualified).toBeGreaterThanOrEqual(2);
    expect(arm.length).toBeGreaterThanOrEqual(2); // soft target 2 is met when >= 2 qualify
    // ordered newest first
    const times = sel.items.map((i) => Date.parse(i.publishedAt));
    expect(times).toEqual([...times].sort((a, b) => b - a));
    // unique ids / urls
    expect(new Set(sel.items.map((i) => i.id)).size).toBe(6);
  });

  it("is reproducible: same fixtures + clock => identical result, independent of input order", () => {
    const a = selectNews(allCandidates(), NOW, cfg);
    const shuffled = allCandidates().reverse();
    const b = selectNews(shuffled, NOW, cfg);
    const c = selectNews([...shuffled.slice(50), ...shuffled.slice(0, 50)], NOW, cfg);
    expect(b.items).toEqual(a.items);
    expect(c.items).toEqual(a.items);
    expect(JSON.stringify(selectNews(allCandidates(), NOW, cfg))).toBe(JSON.stringify(a));
  });

  it("dedupe: the same story from three feeds becomes ONE item (highest-trust source kept) and raises significance", () => {
    const t = new Date(NOW.getTime() - 2 * 3_600_000).toISOString();
    const cands = [
      cand({ title: "Federal Reserve holds interest rate steady as inflation cools", source: "Bloomberg", url: "https://a.example/1", publishedAt: t }),
      cand({ title: "Fed holds interest rates steady as inflation cools", source: "CNBC", feedName: "CNBC", feedId: "cnbc_top", url: "https://b.example/2", publishedAt: t }),
      cand({ title: "Federal Reserve holds interest rate steady as inflation cools - report", source: "Yahoo Finance", feedName: "Yahoo Finance", feedId: "yahoo", url: "https://c.example/3?utm_source=x", publishedAt: t }),
      ...Array.from({ length: 5 }, (_, i) => cand({ title: `Unrelated oil price story number ${i} brent crude`, url: `https://u.example/${i}`, source: `S${i}`, feedName: `S${i}` })),
    ];
    const sel = selectNews(cands, NOW, cfg);
    const fed = sel.items.filter((i) => /interest rate/i.test(i.title));
    expect(fed).toHaveLength(1);
    expect(fed[0].source).toBe("Bloomberg");
    const dbg = sel.debug.find((d) => d.id === fed[0].id)!;
    expect(dbg.clusterSize).toBe(3);
    expect(dbg.significance).toBeGreaterThanOrEqual(1);
    // same canonical URL twice => one
    const twice = selectNews([cand({ title: "Markets steady", url: "https://d.example/x?utm_campaign=1" }), cand({ title: "Something else entirely about oil", url: "https://d.example/x?utm_campaign=1" })].map((c) => ({ ...c, url: canonicalUrl(c.url) })), NOW, cfg);
    expect(twice.counts.afterDedupe).toBe(1);
  });

  it("dedupe tokens: Armenian vs Armenia, prime minister vs PM compare equal", () => {
    const stop = new Set(cfg.stopwords);
    const a = titleTokens("Armenian Prime Minister receives visiting envoy Zorvak Quelm from Synthland", stop, cfg.dedupe);
    const b = titleTokens("Armenia PM receives visiting envoy Zorvak Quelm from Synthland, discusses cooperation", stop, cfg.dedupe);
    expect(jaccard(a, b)).toBeGreaterThanOrEqual(0.6);
    expect(jaccard(titleTokens("Synthetic oil prices fall on supply worries", stop, cfg.dedupe), titleTokens("Synthetic bitcoin steadies through a quiet session", stop, cfg.dedupe))).toBeLessThan(0.3);
  });

  it("freshness windows: global > 48 h and Armenia > 72 h are excluded (relaxed only when short)", () => {
    const fresh = (h: number) => new Date(NOW.getTime() - h * 3_600_000).toISOString();
    const globals = Array.from({ length: 8 }, (_, i) =>
      cand({ title: HEADLINES[i], source: `G${i}`, feedName: `G${i}`, url: `https://g.example/${i}`, publishedAt: fresh(1 + i) }),
    );
    const old = cand({ title: "Ancient stocks earnings wall street", source: "Old", feedName: "Old", url: "https://old.example/1", publishedAt: fresh(60) });
    const sel = selectNews([...globals, old], NOW, cfg);
    expect(sel.items).toHaveLength(6);
    expect(sel.items.some((i) => i.title.startsWith("Ancient"))).toBe(false);
    const armOld = cand({
      title: "Armenia budget tax gdp inflation", region: "armenia", feedId: "armenpress", feedName: "Armenpress", source: "Armenpress", categories: ["Economy"],
      url: "https://arm.example/1", publishedAt: fresh(80),
    });
    expect(selectNews([armOld], NOW, cfg).items).toHaveLength(0);
    const armOk = { ...armOld, id: "n_x", url: "https://arm.example/2", publishedAt: fresh(70) };
    expect(selectNews([armOk], NOW, cfg).items).toHaveLength(1);
    // future-dated (> 1 h ahead) items are ignored
    const future = cand({ title: "Stocks from the future earnings", url: "https://f.example/1", publishedAt: fresh(-5) });
    expect(selectNews([future], NOW, cfg).items).toHaveLength(0);
  });

  it("Armenia quota is SOFT: never forced below relevance 0.3; 1 qualifying item => 1, 0 => fill with global", () => {
    const globals = Array.from({ length: 10 }, (_, i) =>
      cand({ title: HEADLINES[i], source: `G${i % 5}`, feedName: `G${i % 5}`, url: `https://g.example/${i}`, publishedAt: new Date(NOW.getTime() - (i + 1) * 3_600_000).toISOString() }),
    );
    const irrelevant = cand({ title: "Armenia national football team wins", region: "armenia", feedId: "newsam", feedName: "News.am", source: "News.am", url: "https://arm.example/sport" });
    const none = selectNews([...globals, irrelevant], NOW, cfg);
    expect(none.items.filter((i) => i.region === "armenia")).toHaveLength(0);
    expect(none.items).toHaveLength(6);
    const good = cand({ title: "Armenia central bank of armenia raises dram rate, inflation slows", region: "armenia", feedId: "newsam", feedName: "News.am", source: "News.am", url: "https://arm.example/cba" });
    const one = selectNews([...globals, irrelevant, good], NOW, cfg);
    expect(one.items.filter((i) => i.region === "armenia")).toHaveLength(1);
    expect(one.items).toHaveLength(6);
  });

  it("fewer than 6 available: returns what exists with an explanation (never fabricates)", () => {
    const three = Array.from({ length: 3 }, (_, i) => cand({ title: HEADLINES[i], source: `S${i}`, feedName: `S${i}`, url: `https://s.example/${i}` }));
    const sel = selectNews(three, NOW, cfg);
    expect(sel.items).toHaveLength(3);
    expect(sel.shortfall).toMatch(/Only 3 of 6/);
    expect(selectNews([], NOW, cfg).items).toEqual([]);
  });

  it("diversity caps relax in order (topic, then source) only when needed", () => {
    // 6 stories all in one topic from 3 sources: strict caps (2 per topic) can't reach 6 -> relaxation is reported
    const cands = Array.from({ length: 6 }, (_, i) =>
      cand({ title: EQUITY_HEADLINES[i], source: `S${i % 3}`, feedName: `S${i % 3}`, url: `https://s.example/${i}`, publishedAt: new Date(NOW.getTime() - (i + 1) * 3_600_000).toISOString() }),
    );
    const sel = selectNews(cands, NOW, cfg);
    expect(sel.items.length).toBeGreaterThan(2);
    expect(sel.relaxed.length).toBeGreaterThan(0);
    expect(sel.relaxed[0]).toBe("topicCap");
  });
});

describe("structural features of the synthetic fixtures are really exercised", () => {
  const raw = (file: string) => parseFeed(fixture("rss", `${file}.xml`), file);
  const cands = allCandidates();
  const NOW_MS = NOW.getTime();

  it("every fixture file is labelled synthetic and uses only example.test URLs", () => {
    for (const f of Object.values(FILES)) {
      const xml = fixture("rss", `${f}.xml`);
      expect(xml, f).toContain("<!-- SYNTHETIC TEST DATA - invented text, not real news -->");
      const hosts = new Set([...xml.matchAll(/https?:\/\/([a-z0-9.-]+)/gi)].map((m) => m[1].toLowerCase()));
      for (const h of hosts) expect(["example.test", "purl.org", "www.w3.org", "search.yahoo.com"].includes(h) || h.endsWith("w3.org"), `${f}: ${h}`).toBe(true);
    }
  });

  it("opinion / sport / sponsored items are in the raw feed but never become candidates", () => {
    const rawTitles = raw("guardian_business").map((i) => i.title);
    expect(rawTitles.some((t) => /^Synthetic Opinion/.test(t))).toBe(true);
    expect(rawTitles.some((t) => /^Synthetic Sport/.test(t))).toBe(true);
    expect(rawTitles.some((t) => /^Synthetic Sponsored/.test(t))).toBe(true);
    expect(cands.some((c) => /^Synthetic (Opinion|Sport|Sponsored)/.test(c.title))).toBe(false);
    expect(cands.some((c) => c.url.includes("/live/"))).toBe(false); // live blogs are excluded by URL pattern
    // Armenpress Culture items are dropped by category
    const cultureRaw = raw("armenpress").filter((i) => i.categories.includes("Culture")).length;
    expect(cultureRaw).toBeGreaterThan(0);
    expect(cands.filter((c) => c.feedId === "armenpress" && c.categories.includes("Culture"))).toHaveLength(0);
  });

  it("tracking parameters are stripped from canonical URLs (raw links carry utm_*)", () => {
    expect(raw("yahoo").some((i) => /utm_/.test(i.link))).toBe(true);
    expect(raw("nyt_business").some((i) => /utm_/.test(i.link))).toBe(true);
    expect(cands.some((c) => /utm_/.test(c.url))).toBe(false);
    expect(new Set(cands.map((c) => c.id)).size).toBeLessThan(cands.length); // same canonical URL from several feeds => same id
  });

  it("parser features: NYT <link> + <atom:link> collision, CDATA titles with whitespace, escaped-HTML descriptions, insecure images dropped", () => {
    expect(raw("nyt_business")[0].link).toMatch(/^https:\/\/example\.test\/nyt\//);
    expect(raw("armenpress")[0].title).toMatch(/^Synthetic Headline/);
    const g = raw("guardian_business").find((i) => i.summary)!;
    expect(g.summary).toMatch(/^Synthetic summary/);
    expect(g.summary).not.toMatch(/[<>]|&lt;/);
    const y = raw("yahoo");
    expect(y.some((i) => i.imageUrl === null)).toBe(true); // items without media or with an http:// image
    expect(fixture("rss", "yahoo.xml")).toContain("http://example.test/img/");
    expect(y.every((i) => i.imageUrl === null || i.imageUrl.startsWith("https://"))).toBe(true);
    expect(raw("bbc_business").every((i) => i.imageUrl === null || i.imageUrl.startsWith("https://"))).toBe(true); // media:thumbnail
    expect(raw("armenpress").some((i) => i.imageUrl?.endsWith(".webp"))).toBe(true); // enclosure
    expect(raw("guardian_business").some((i) => i.imageUrl)).toBe(true); // media:content
    expect(raw("newsam").every((i) => i.summary === null)).toBe(true); // feed without descriptions
  });

  it("stale items exist in the pool but the selection only contains fresh ones (global <= 48 h, Armenia <= 72 h)", () => {
    const stale = cands.filter((c) => (NOW_MS - Date.parse(c.publishedAt)) / 3_600_000 > (c.region === "armenia" ? 72 : 48));
    expect(stale.length).toBeGreaterThan(10);
    const sel = selectNews(cands, NOW, cfg);
    expect(sel.counts.afterFilter).toBeLessThan(sel.counts.candidates);
    // (the same URL can appear in several feeds with different timestamps, so compare id AND timestamp)
    for (const i of sel.items) expect(stale.some((s) => s.id === i.id && s.publishedAt === i.publishedAt)).toBe(false);
    for (const i of sel.items) expect((NOW_MS - Date.parse(i.publishedAt)) / 3_600_000).toBeLessThanOrEqual(i.region === "armenia" ? 72 : 48);
  });

  it("cross-feed near-duplicates collapse: each story number appears once in the six, and multi-feed clusters are detected", () => {
    const storyNo = (t: string) => /Synthetic Headline (\d+)/.exec(t)![1];
    for (const n of ["901", "902", "903", "951", "952", "953"]) {
      const feeds = new Set(cands.filter((c) => storyNo(c.title) === n).map((c) => c.feedId));
      expect(feeds.size, `story ${n}`).toBeGreaterThanOrEqual(3);
    }
    const sel = selectNews(cands, NOW, cfg);
    const nums = sel.items.map((i) => storyNo(i.title));
    expect(new Set(nums).size).toBe(nums.length);
    expect(sel.counts.afterDedupe).toBeLessThan(sel.counts.afterFilter);
    const big = sel.debug.filter((d) => d.clusterSize >= 3);
    expect(big.length).toBeGreaterThanOrEqual(4);
    expect(big.every((d) => d.significance > 0)).toBe(true);
  });

  it("the Armenia pool only admits Armenia-relevant items: World/off-topic and entity-less items are not selectable", () => {
    const nsam = cands.filter((c) => c.feedId === "newsam");
    expect(nsam.length).toBe(60); // poolMaxItemsPerFeed
    const sel = selectNews(cands, NOW, cfg);
    for (const i of sel.items.filter((x) => x.region === "armenia")) {
      expect(i.title).toMatch(/dram|central bank|GDP|budget|tax|export|IT sector|mining|fuel|mortgage|energy|investment|pension|Armenia/i);
      expect(i.title).not.toMatch(/ferry|museum|cycling|airport|heatwave|university|folk festival|ministers attend|sports team|delegation/i);
    }
    expect(sel.counts.armeniaQualified).toBeGreaterThanOrEqual(10);
  });
});

describe("news service (cache, stale, refresh throttle) with synthetic feeds", () => {
  let user: TestUser;
  let other: TestUser;
  let mock: FetchMock | undefined;
  let fetchCalls = 0;

  beforeAll(async () => {
    await useTestDb();
    user = await registerUser("news");
    other = await registerUser("news2");
  });
  beforeEach(async () => {
    await resetCache();
    fetchCalls = 0;
    setNewsFetchers({
      now: () => NOW,
      fetchFeed: async (f) => {
        fetchCalls++;
        return fixtureFetch(f);
      },
    });
  });
  afterEach(() => {
    setNewsFetchers(null);
    mock?.restore();
  });

  it("GET /api/market/news: 401 anonymous; 200 with exactly 6 items, meta, no bodies; second call served from cache", async () => {
    expect((await call(newsRoute.GET, "GET", "/api/market/news")).status).toBe(401);
    const r = await call(newsRoute.GET, "GET", "/api/market/news", { jar: user.jar });
    expect(r.status).toBe(200);
    expect(r.body.data.items).toHaveLength(6);
    expect(r.body.meta).toMatchObject({ stale: false, isFixture: false });
    expect(r.body.meta.asOf).toMatch(/^\d{4}-\d\d-\d\dT/);
    expect(JSON.stringify(r.body)).not.toMatch(/description|content:encoded|enclosure|<p>|<img/i);
    const callsAfterFirst = fetchCalls;
    expect(callsAfterFirst).toBeGreaterThanOrEqual(10);
    const r2 = await call(newsRoute.GET, "GET", "/api/market/news", { jar: user.jar });
    expect(fetchCalls).toBe(callsAfterFirst);
    expect(r2.body.data).toEqual(r.body.data);
  });

  it("one failing/timeouting feed is skipped; the rest still produce six", async () => {
    setNewsFetchers({
      now: () => NOW,
      fetchFeed: async (f) => {
        if (f.id === "yahoo" || f.id === "armenpress") throw new Error("timeout");
        return fixtureFetch(f);
      },
    });
    const n = await getNews();
    expect(n.data.items).toHaveLength(6);
    expect(n.meta.feeds.filter((f) => !f.ok).map((f) => f.id).sort()).toEqual(["armenpress", "yahoo"]);
    expect(n.data.items.some((i) => i.source === "Yahoo Finance")).toBe(false);
  });

  it("all feeds down: the last good six are served with stale:true; with an empty cache it is a 503, never fake data", async () => {
    const good = await getNews();
    setNewsFetchers({ now: () => NOW, fetchFeed: async () => { throw new Error("network down"); } });
    const stale = await getNews({ forceRefresh: true });
    expect(stale.meta.stale).toBe(true);
    expect(stale.data.items).toEqual(good.data.items);
    expect(stale.meta.staleReason).toMatch(/network down|All news feeds failed/);
    await resetCache();
    const r = await call(newsRoute.GET, "GET", "/api/market/news", { jar: user.jar });
    expect(r.status).toBe(503);
    expect(r.body.error.code).toBe("UPSTREAM_UNAVAILABLE");
  });

  it("malformed feed XML does not break the pipeline", async () => {
    setNewsFetchers({
      now: () => NOW,
      fetchFeed: async (f) => (f.id === "bbc_business" ? "<html>not a feed" : fixtureFetch(f)),
    });
    const n = await getNews();
    expect(n.data.items).toHaveLength(6);
    expect(n.meta.feeds.find((f) => f.id === "bbc_business")!.ok).toBe(false);
  });

  it("POST /refresh: throttled 1 per 30 s per user (429 + Retry-After); other users unaffected; young cache is not re-fetched", async () => {
    expect((await call(refreshRoute.POST, "POST", "/api/market/news/refresh")).status).toBe(401);
    await getNews(); // warm cache
    const before = fetchCalls;
    const first = await call(refreshRoute.POST, "POST", "/api/market/news/refresh", { jar: user.jar });
    expect(first.status).toBe(200);
    expect(first.body.data.items).toHaveLength(6);
    expect(fetchCalls).toBe(before); // cache is younger than 5 minutes -> no upstream call
    const second = await call(refreshRoute.POST, "POST", "/api/market/news/refresh", { jar: user.jar });
    expect(second.status).toBe(429);
    expect(second.body.error.code).toBe("RATE_LIMITED");
    expect(Number(second.headers.get("retry-after"))).toBeGreaterThan(0);
    expect(Number(second.headers.get("retry-after"))).toBeLessThanOrEqual(30);
    const third = await call(refreshRoute.POST, "POST", "/api/market/news/refresh", { jar: other.jar });
    expect(third.status).toBe(200);
  });

  it("100 concurrent requests on a cold cache cause ONE upstream fetch per feed (single-flight + DB lock)", async () => {
    const responses = await Promise.all(Array.from({ length: 100 }, () => call(newsRoute.GET, "GET", "/api/market/news", { jar: user.jar })));
    expect(responses.every((r) => r.status === 200)).toBe(true);
    const feedsEnabled = cfg.feeds.filter((f) => f.enabled).length;
    expect(fetchCalls).toBe(feedsEnabled);
  });
});
